{% set name = "ome-types" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ome_types-{{ version }}.tar.gz
  sha256: 434703bbd4079f7c8227fb074988c11a2d5e8cdbfbfc18675e45540eea6285e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
    - hatch-vcs
    - black
    - isort >=5.0
    - xmlschema >=1.4.1,<2
    - autoflake
    - numpydoc
  run:
    - lxml >=4.8.0
    - pint >=0.15
    - pydantic >=1.0
    - python >=3.7
    - xmlschema >=1.4.1,<2

test:
  imports:
    - ome_types
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/ome-types
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: native python dataclasses for the OME data model
  doc_url: https://ome-types.readthedocs.io/en/latest/
  dev_url: https://github.com/tlambert03/ome-types

extra:
  recipe-maintainers:
    - tlambert03
