{% set name = "ome-types" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b6113ca12501975d56152a2117dc6c40da95448689300a380fcb38b0e99f6b4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
    - isort >=5.0
    - black
    - autoflake
    - numpydoc
    - xmlschema ==1.4.1

  run:
    - python >=3.7
    - pydantic
    - xmlschema ==1.4.1
    - Pint >=0.15

test:
  imports:
    - ome_types
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tlambert03/ome-types
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: native python dataclasses for the OME data model
  doc_url: https://ome-types.readthedocs.io/en/latest/
  dev_url: https://github.com/tlambert03/ome-types

extra:
  recipe-maintainers:
    - tlambert03
