{% set name = "ome-types" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ome_types-{{ version }}.tar.gz
  sha256: 971139bf5b85d6492937f2fee75c03e05bd20043ac01e78e3b00991cb41cfa7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - autoflake
    - black
    - isort >=5.0
    - numpydoc
    - pip
    - pydantic <2.0
    - python >=3.7
    - setuptools >=42
    - setuptools-scm
    - wheel
    - xmlschema ==1.4.1
  run:
    - lxml >=4.8.0
    - pint >=0.15
    - pydantic <2.0
    - python >=3.7
    - xmlschema >=1.4.1,<2

test:
  imports:
    - ome_types
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/ome-types
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: native python dataclasses for the OME data model
  doc_url: https://ome-types.readthedocs.io/en/latest/
  dev_url: https://github.com/tlambert03/ome-types

extra:
  recipe-maintainers:
    - tlambert03
