{% set name = "ome-types" %}
{% set version = "0.5.1.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ome_types-{{ version }}.tar.gz
  sha256: cadda5e36ad4d33dad2034fd43f32113a736fe47c67fd9e06bbb8d3858d1dc58

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
    - pydantic-compat >=0.1.0
    - pydantic >=1.9.0
    - xsdata ==24.2.1
    - ruff ==0.3.0
  run:
    - python >=3.8
    - pydantic >=1.9.0
    - pydantic-compat >=0.1.0
    - xsdata >=23.6,<25  # includes all the cli extras
    # extras
    - lxml >=4.8.0
    - pint >=0.15

test:
  imports:
    - ome_types
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/ome-types
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: native python dataclasses for the OME data model
  doc_url: https://ome-types.readthedocs.io/en/latest/
  dev_url: https://github.com/tlambert03/ome-types

extra:
  recipe-maintainers:
    - tlambert03
