{% set name = "ome-types" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ome_types-{{ version }}.tar.gz
  sha256: 5027dca479ed23f60035e7b097a745db7de029cc6034a2a2eb39a29848eff3f3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling
    - hatch-vcs
    - pydantic >=1.9.0
    - xsdata >=23.6  # includes all the cli extras
    - black
    - ruff
  run:
    - python >=3.7
    - pydantic >=1.9.0
    - xsdata >=23.5
    - importlib_metadata
    # extras
    - lxml >=4.8.0
    - pint >=0.15

test:
  imports:
    - ome_types
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/ome-types
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: native python dataclasses for the OME data model
  doc_url: https://ome-types.readthedocs.io/en/latest/
  dev_url: https://github.com/tlambert03/ome-types

extra:
  recipe-maintainers:
    - tlambert03
