schema_version: 1

context:
  name: ome-types
  version: 0.6.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/ome_types-${{ version }}.tar.gz
  sha256: 49e7a79ac90f8e4c33392f285491cb2577d41f2583bb879307c4f5ba9436e721

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pydantic >=2.4
    - pydantic-extra-types
    - xsdata ==24.2.1
    - ruff
  run:
    - python >=${{ python_min }}
    - pydantic >=2.4
    - pydantic-extra-types
    - xsdata >=23.6,<24.4  # includes all the cli extras
    # extras
    - lxml >=4.8.0
    - pint >=0.15

tests:
  - python:
      imports:
        - ome_types
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip list
      - pip check

about:
  license: MIT
  license_file: LICENSE
  summary: native python dataclasses for the OME data model
  homepage: https://github.com/tlambert03/ome-types
  repository: https://github.com/tlambert03/ome-types
  documentation: https://ome-types.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - tlambert03
